name: ArenaRegenerator
version: ${project.version}
main: io.github.woodstop.arenaRegenerator.ArenaRegenerator
author: Woodstop
api-version: '1.21'
softdepend: [FastAsyncWorldEdit, WorldEdit]
commands:
  arena:
    description: "Main command for ArenaRegenerator plugin."
    usage: "/arena <save|regen|clear|list|delete|info|select|join|leave|reload|setspawn|delspawn> [arenaName]"
    aliases: [ ar ]

permissions:
  arenaregenerator.*:
    description: Grants all ArenaRegenerator permissions.
    default: op
    children:
      arenaregenerator.save: true
      arenaregenerator.regen: true
      arenaregenerator.clear: true
      arenaregenerator.list: true
      arenaregenerator.delete: true
      arenaregenerator.info: true
      arenaregenerator.select: true
      arenaregenerator.join: true
      arenaregenerator.leave: true
      arenaregenerator.reload: true
      arenaregenerator.setspawn: true
      arenaregenerator.delspawn: true
      arenaregenerator.sign.create.regen: true
      arenaregenerator.sign.create.join: true
      arenaregenerator.sign.create.leave: true
      arenaregenerator.sign.use.regen: true
      arenaregenerator.sign.use.join: true
      arenaregenerator.sign.use.leave: true
      arenaregenerator.sign.bypass: true
      arenaregenerator.sign.break: true
  arenaregenerator.save:
    description: Allows saving arenas.
    default: op
  arenaregenerator.regen:
    description: Allows regenerating arenas.
    default: op
  arenaregenerator.clear:
    description: Allows clearing arenas.
    default: op
  arenaregenerator.list:
    description: Allows listing arenas.
    default: op
  arenaregenerator.delete:
    description: Allows deleting arenas.
    default: op
  arenaregenerator.info:
    description: Allows getting arena info.
    default: op
  arenaregenerator.select:
    description: Allows selecting arenas.
    default: op
  arenaregenerator.join:
    description: Allows joining minigame arenas.
    default: op
  arenaregenerator.leave:
    description: Allows leaving minigame arenas
    default: true
  arenaregenerator.reload:
    description: Allows reloading the plugin configuration.
    default: op
  arenaregenerator.setspawn:
    description: Allows setting lobby, exit, spectator, and game spawns.
    default: op
  arenaregenerator.delspawn:
    description: Allows deleting lobby, exit, spectator, and game spawns.
    default: op
  arenaregenerator.sign.create.regen:
    description: Allows creating [RegenArena] signs.
    default: op
  arenaregenerator.sign.create.join:
    description: Allows creating [JoinArena] signs.
    default: op
  arenaregenerator.sign.create.leave:
    description: Allows creating [LeaveArena] signs.
    default: op
  arenaregenerator.sign.use.regen:
    description: Allows using [RegenArena] signs.
    default: false
  arenaregenerator.sign.use.join:
    description: Allows using [JoinArena] signs.
    default: op
  arenaregenerator.sign.use.leave:
    description: Allows using [LeaveArena] signs.
    default: true
  arenaregenerator.sign.bypass:
    description: Allows bypassing cooldown on [RegenArena] signs.
    default: op
  arenaregenerator.sign.break:
    description: Allows breaking [RegenArena] signs.
    default: op
