name: ArenaRegenerator
version: ${project.version}
main: io.github.woodstop.arenaRegenerator.ArenaRegenerator
api-version: '1.21'
softdepend: [FastAsyncWorldEdit, WorldEdit]
commands:
    arena:
      description: "Main command for ArenaRegenerator plugin."
      usage: "/arena <save|regen|clear|list|delete|info|select|join|leave> [arenaName]"
      permission: arenaregenerator.command
      aliases: [ ar ]
permissions:
  arenaregenerator.command:
    description: Allows access to the /arena command and its subcommands.
    default: op
    children:
      arenaregenerator.save: true
      arenaregenerator.regen: true
      arenaregenerator.clear: true
      arenaregenerator.list: true
      arenaregenerator.delete: true
      arenaregenerator.info: true
      arenaregenerator.select: true
      arenaregenerator.join: true
      arenaregenerator.leave: true
      arenaregenerator.reload: true
  arenaregenerator.save:
    description: "Saves the specified region as a schematic"
    default: op
  arenaregenerator.regen:
    description: "Regenerates the arena"
    default: op
  arenaregenerator.clear:
    description: "Clears the blocks in an arena without deleting the schematic"
    default: op
  arenaregenerator.list:
    description: "Provides a list of arenas"
    default: op
  arenaregenerator.delete:
    description: "Deletes the specified arena"
    default: op
  arenaregenerator.info:
    description: "Show metadata for a saved arena"
    default: op
  arenaregenerator.select:
    description: "Selects the specified arena"
    default: op
  arenaregenerator.join:
    description: "Allows joining minigame arenas"
    default: true
  arenaregenerator.leave:
    description: "Allows leaving minigame arenas"
    default: true
  arenaregenerator.reload:
    description: "Allows reloading the plugin configuration."
    default: op
  arenaregenerator.sign.create:
    default: op
  arenaregenerator.sign.use:
    default: op
  arenaregenerator.sign.bypass:
    default: op
  arenaregenerator.sign.break:
    default: op